spring:
  application:
    name: usercenter
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.130:8848
        secure: false
  datasource:
    ## mysql\u6570\u636E\u5E93 5.6\u4EE5\u540E\u8981\u4F7F\u7528\u5E26cj\u7684\u9A71\u52A8\u7A0B\u5E8F
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.174.130:3306/usercenter?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

token:
  header: Authorization
  secret: fjdhs&*^*98
  # 令牌有效时间（默认30分钟）
  expire: 3600000
